version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test:unit
      - run: npm run test:e2e:headless:chrome